/*
 * Guideline 18 - Beware the Performance of Acyclic Visitor
 *
 * The classic (GoF) Visitor has a CYCLIC dependency: the Visitor base class
 * lists one visit overload per concrete shape (visit for Circle, visit for
 * Square, ...), the shapes depend on the Shape base, and the Shape base depends
 * on the Visitor base. That cycle locks every key player onto one level of the
 * architecture, so adding a NEW TYPE forces an edit to the shared Visitor base
 * and recompiles everything. You can keep operations open OR types open, not
 * both.
 *
 * The ACYCLIC VISITOR breaks the cycle. It splits the single Visitor base into:
 *   - AbstractVisitor: an EMPTY base with only a virtual destructor. It is just
 *     a tag that says "I am some visitor". It names no shape, so it depends on
 *     nothing below it.
 *   - Visitor<T>: one tiny per-type interface, generated by a template. A
 *     concrete operation inherits AbstractVisitor plus a Visitor<Shape> for
 *     each shape it chooses to support.
 * Now nothing on the high level names a concrete shape, so you can add both new
 * TYPES and new OPERATIONS without touching shared code. Adding Triangle below
 * needs no edit to AbstractVisitor or to the existing shapes.
 *
 * The catch, and the whole point of this guideline: each accept() must recover
 * the concrete visitor interface with a dynamic_cast. That cast is a CROSS-CAST
 * (it jumps sideways from the AbstractVisitor base subobject into the sibling
 * Visitor<T> branch of a multiple-inheritance hierarchy), and a cross-cast plus
 * the following virtual call is far costlier than a plain virtual dispatch. The
 * book measures the Acyclic Visitor at roughly an order of magnitude slower than
 * the cyclic Visitor. This sample reproduces that gap with a small benchmark:
 * the dynamic_cast path versus a direct virtual call that computes the same sum.
 *
 * Key notes:
 *   - AbstractVisitor is an empty, purely polymorphic tag base. dynamic_cast
 *     needs a polymorphic source, which its virtual destructor provides.
 *   - Acyclic Visitor wins on architecture: both axes of extension stay open
 *     because no high-level type names a concrete shape.
 *   - Acyclic Visitor loses on speed: every visitation pays for a cross-cast
 *     via RTTI, then a virtual call. The timing block makes that cost concrete.
 *   - The benchmark uses modest iteration counts and prints the matching sums
 *     so the optimizer cannot discard the work; treat the numbers as
 *     qualitative, exactly as the book does.
 */
#include <chrono>
#include <iostream>
#include <memory>
#include <numbers>
#include <vector>

// The empty tag base. It owns no operation; its only job is to be polymorphic
// so that a dynamic_cast can probe it for a concrete visitor interface. Adding
// a new shape NEVER edits this class, which is what breaks the cyclic
// dependency of the classic Visitor.
class AbstractVisitor
{
public:
    virtual ~AbstractVisitor() = default;
};

// One small visitor interface per shape type, produced by a template. An
// operation inherits Visitor<Circle> only if it wants to support circles. The
// protected destructor keeps callers from deleting through this partial base.
template <typename T>
class Visitor
{
protected:
    ~Visitor() = default;

public:
    virtual void visit(const T&) const = 0;
};

// The Shape base now depends only on the empty AbstractVisitor, not on any
// concrete visitor that names concrete shapes. That is the broken cycle.
class Shape
{
public:
    virtual ~Shape() = default;
    virtual void accept(const AbstractVisitor& v) const = 0;

    // A direct virtual operation used by the benchmark as the fast baseline.
    virtual double area() const = 0;
};

class Circle : public Shape
{
public:
    explicit Circle(double radius) : m_radius{radius} {}

    // The acyclic visitation step. Probe the abstract visitor for the
    // Circle-specific interface with a dynamic_cast cross-cast; if it supports
    // circles, dispatch. This cast is the slow part the guideline warns about.
    void accept(const AbstractVisitor& v) const override
    {
        if (const auto* cv = dynamic_cast<const Visitor<Circle>*>(&v))
        {
            cv->visit(*this);
        }
    }

    double area() const override { return std::numbers::pi * m_radius * m_radius; }
    double radius() const { return m_radius; }

private:
    double m_radius;
};

class Square : public Shape
{
public:
    explicit Square(double side) : m_side{side} {}

    void accept(const AbstractVisitor& v) const override
    {
        if (const auto* sv = dynamic_cast<const Visitor<Square>*>(&v))
        {
            sv->visit(*this);
        }
    }

    double area() const override { return m_side * m_side; }
    double side() const { return m_side; }

private:
    double m_side;
};

// Adding a NEW TYPE costs nothing on the high level. Triangle just supplies its
// own accept() probing Visitor<Triangle>. AbstractVisitor, Circle and Square
// are untouched. In a classic cyclic Visitor this would force editing the
// shared Visitor base and recompiling every shape and every visitor.
class Triangle : public Shape
{
public:
    Triangle(double base, double height) : m_base{base}, m_height{height} {}

    void accept(const AbstractVisitor& v) const override
    {
        if (const auto* tv = dynamic_cast<const Visitor<Triangle>*>(&v))
        {
            tv->visit(*this);
        }
    }

    double area() const override { return 0.5 * m_base * m_height; }
    double base() const { return m_base; }
    double height() const { return m_height; }

private:
    double m_base;
    double m_height;
};

// A concrete operation. It opts into the three shapes by inheriting their
// per-type interfaces plus the AbstractVisitor tag. Note that supporting
// Triangle here is also additive: no existing class changed.
class Draw : public AbstractVisitor
           , public Visitor<Circle>
           , public Visitor<Square>
           , public Visitor<Triangle>
{
public:
    void visit(const Circle& c) const override
    {
        std::cout << "  Circle(r=" << c.radius() << ") area=" << c.area() << '\n';
    }
    void visit(const Square& s) const override
    {
        std::cout << "  Square(s=" << s.side() << ") area=" << s.area() << '\n';
    }
    void visit(const Triangle& t) const override
    {
        std::cout << "  Triangle(b=" << t.base() << ", h=" << t.height()
                  << ") area=" << t.area() << '\n';
    }
};

// A second operation that only accumulates area, used by the benchmark so the
// per-visitation work is tiny and the dynamic_cast dominates the timing.
class AreaSum : public AbstractVisitor
              , public Visitor<Circle>
              , public Visitor<Square>
              , public Visitor<Triangle>
{
public:
    explicit AreaSum(double& acc) : m_acc{acc} {}

    void visit(const Circle& c) const override { m_acc += c.area(); }
    void visit(const Square& s) const override { m_acc += s.area(); }
    void visit(const Triangle& t) const override { m_acc += t.area(); }

private:
    double& m_acc;
};

int main()
{
    std::vector<std::unique_ptr<Shape>> shapes;
    shapes.push_back(std::make_unique<Circle>(2.3));
    shapes.push_back(std::make_unique<Square>(1.2));
    // The new TYPE plugs in with zero edits to the visitor bases:
    shapes.push_back(std::make_unique<Triangle>(3.0, 4.0));

    std::cout << "Acyclic Visitor - drawing via dynamic_cast dispatch:\n";
    const Draw drawer;
    for (const auto& shape : shapes)
    {
        shape->accept(drawer);
    }

    // --- Tiny timing note: dynamic_cast visitation vs direct virtual call ---
    // Both loops compute the same total area. The only difference is HOW the
    // shape work is reached: through the acyclic visitor's cross-cast, or
    // through one plain virtual call. Keep counts modest; numbers are
    // qualitative.
    constexpr int iterations = 200000;
    using clock = std::chrono::steady_clock;

    double acyclicSum = 0.0;
    {
        const AreaSum summer{acyclicSum};
        const auto start = clock::now();
        for (int i = 0; i < iterations; ++i)
        {
            for (const auto& shape : shapes)
            {
                shape->accept(summer); // dynamic_cast cross-cast then virtual call
            }
        }
        const auto stop = clock::now();
        const auto ms =
            std::chrono::duration_cast<std::chrono::milliseconds>(stop - start);
        std::cout << "\nAcyclic (dynamic_cast) : sum=" << acyclicSum
                  << "  time=" << ms.count() << " ms\n";
    }

    double directSum = 0.0;
    {
        const auto start = clock::now();
        for (int i = 0; i < iterations; ++i)
        {
            for (const auto& shape : shapes)
            {
                directSum += shape->area(); // single virtual call, no cast
            }
        }
        const auto stop = clock::now();
        const auto ms =
            std::chrono::duration_cast<std::chrono::milliseconds>(stop - start);
        std::cout << "Direct (virtual call)  : sum=" << directSum
                  << "  time=" << ms.count() << " ms\n";
    }

    std::cout << "\nObservation: both paths produce the same sum, but the\n"
                 "dynamic_cast path is markedly slower. The cross-cast plus\n"
                 "virtual call is the price of the Acyclic Visitor's open,\n"
                 "acyclic design. Architecturally elegant, but measure before\n"
                 "you adopt it on a hot path.\n";
    return 0;
}
